Feature/admin panel
saparjohnick/task_manager pull request #11
Opened 2021-10-31 12:15 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/78/practices

2021-11-01 20:17 UTC, greybutton requested changes
1 проверь рубокоп
2 не хватает изменений в app/views/layouts/application.html.slim

2021-11-01 20:17 UTC, greybutton commented on app/helpers/application_helper.rb
> +  include AuthHelper
почему добавил?

2021-11-01 20:17 UTC, greybutton commented on app/views/admin/users/edit.html.slim
> +  == render partial: 'form', locals: {f: f}
форма получилась разорваной simple_form_for в одном месте, f.input в другом

2021-11-01 20:17 UTC, greybutton commented on app/views/admin/users/new.html.slim
> +  == render partial: 'form', locals: { f: f }
тоже разорванная форма

2021-11-03 11:17 UTC, saparjohnick commented on app/helpers/application_helper.rb
> +  include AuthHelper
без нее тесты падают. (не видят `current_user`)

2021-11-03 11:21 UTC, saparjohnick commented
Спасибо, вроде все исправил. Немного выпадал из процесса из-за последствий после прививки.

2021-11-03 11:22 UTC, saparjohnick commented on app/views/admin/users/edit.html.slim
> +  == render partial: 'form', locals: {f: f}
переделал тут https://github.com/saparjohnick/task_manager/pull/11/commits/2836f7bf62ce023a9284a4d310fd987702f4e116

2021-11-03 11:22 UTC, saparjohnick commented on app/views/admin/users/new.html.slim
> +  == render partial: 'form', locals: { f: f }
переделал тут https://github.com/saparjohnick/task_manager/pull/11/commits/2836f7bf62ce023a9284a4d310fd987702f4e116

2021-11-03 15:38 UTC, greybutton requested changes

2021-11-03 15:38 UTC, greybutton commented on app/helpers/application_helper.rb
> +  include AuthHelper
уверен, что сюда нужно добавлять? добавлено в test/test_helper.rb, по идее здесь не нужно. Проверь плис

2021-11-03 15:38 UTC, greybutton commented on app/views/admin/users/_form.html.slim
> +h4 #{headline}
лишняя переменная, это можно оставить в edit и new

2021-11-03 17:03 UTC, saparjohnick commented on app/helpers/application_helper.rb
> +  include AuthHelper
да, я проверял -- если строчку закомментить - тесты красные, раскомментить - зеленые

2021-11-03 17:08 UTC, saparjohnick commented on app/views/admin/users/_form.html.slim
> +h4 #{headline}
спасибо, убрал https://github.com/saparjohnick/task_manager/pull/11/commits/b1024b964e2d511a635e09b473bd8074bc1c89d8

2021-11-03 17:21 UTC, saparjohnick commented on app/helpers/application_helper.rb
> +  include AuthHelper
перед коммитом проверил на всякий еще раз, то же самое

2021-11-03 17:41 UTC, greybutton approved these changes

2021-11-03 18:30 UTC, merged