Feature/api
saparjohnick/task_manager pull request #12
Opened 2021-10-31 21:16 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/79/practices -- TaskManager. API.

2021-11-01 20:23 UTC, greybutton requested changes
проверь рубокоп

2021-11-01 20:23 UTC, greybutton commented on app/controllers/api/application_controller.rb
> +  include AuthHelper
это в Api::ApplicationController

2021-11-01 20:23 UTC, greybutton commented on app/controllers/api/application_controller.rb
> +  end
это в Api::V1::ApplicationController

2021-11-01 20:23 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +  respond_to :json
это в Api::ApplicationController

2021-11-01 20:23 UTC, greybutton commented on test/factories/tasks.rb
> -    expired_at
отсюда удалять не нужно, а нужно добавить поле в task_params

2021-11-01 20:23 UTC, greybutton commented on test/factories/sequence.rb
> -
это тоже вернуть

2021-11-03 18:46 UTC, saparjohnick commented
вроде исправил https://github.com/saparjohnick/task_manager/pull/12/commits/ea7a71a5ae321a2a1a81d82014351eede0503108
https://github.com/saparjohnick/task_manager/pull/12/commits/dd28f5a7df1df9435a81c2aaff5d65a7e6e2cff3

2021-11-05 08:57 UTC, greybutton approved these changes

2021-11-05 10:22 UTC, merged