Feature/js init
saparjohnick/task_manager pull request #13
Opened 2021-11-05 18:48 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/88/practices/

2021-11-07 14:17 UTC, moklidia requested changes

2021-11-07 14:17 UTC, moklidia commented on app/javascript/components/TaskBoard/taskBoard.js
> +debugger;
Не оставляй брейкпойнты в коде.

2021-11-07 18:16 UTC, saparjohnick commented on app/javascript/components/TaskBoard/taskBoard.js
> +debugger;
Убрал, спасибо

2021-11-08 06:42 UTC, moklidia approved these changes

2021-11-08 10:43 UTC, merged