Feature/tasks
saparjohnick/task_manager pull request #15
Opened 2021-11-22 22:24 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/81/practices/
(add/delete/edit tasks on kanban board)

2021-11-25 07:22 UTC, greybutton requested changes

2021-11-25 07:22 UTC, greybutton commented on .vscode/launch.json
> +}
добавь .vscode в гитигнор и удали этот файл из мерджа

2021-11-25 07:22 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(RANSACK_DEFAULT_SORT)
не нужно добавлять ордер, он через рансак будет выбираться фронтом

2021-11-25 07:22 UTC, greybutton commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const totalCount = column.meta.total_count;
на пару строк выше можно достать totalCount

2021-11-25 07:22 UTC, greybutton commented on app/javascript/components/TaskBoard/taskBoard.js
> +import TasksRepository from '../../repositories/TasksRepository';
from 'repositories/TasksRepository';

2021-11-25 07:22 UTC, greybutton commented on app/javascript/components/TaskBoard/taskBoard.js
> +  const [currentPage, setCurrentPage] = useState(2);
1 почему 2? 
2 не очень понял код связанный с currentPage, выглядит лишним, тем более бэк отдает текущую страницу

2021-11-25 07:22 UTC, greybutton commented on app/javascript/components/TaskBoard/taskBoard.js
> +    loadColumn(state, currentPage, perPage).then(({ data }) => {
зачем currentPage если есть page?

2021-11-25 07:22 UTC, greybutton commented on app/controllers/api/v1/application_controller.rb
> +      page: collection.current_page,
зачем переименовывать?

2021-11-25 07:22 UTC, greybutton commented on app/javascript/components/TaskBoard/taskBoard.js
> +          <div>
необязательно в див оборачивать

2021-11-25 07:22 UTC, greybutton commented on app/javascript/utils/fetchHelper.js
> +      .then(camelize(params));
здесь params не нужны

2021-11-25 07:22 UTC, greybutton commented on config/environments/development.rb
> +  config.web_console.whitelisted_ips = '172.19.0.1'
это зачем?

2021-11-25 07:22 UTC, greybutton commented on package.json
> +    "ramda": "^0.27.1",
qs не хватает

2021-11-25 07:22 UTC, greybutton commented on app/javascript/components/TaskBoard/taskBoard.js
> +              isButtonHidden={buttonState}
как то странно что стейт превращается в булево. и изначально это не стейт, а булево

2021-11-25 21:38 UTC, saparjohnick commented on app/controllers/api/v1/tasks_controller.rb
> +      order(RANSACK_DEFAULT_SORT)
без него не сортирует почему-то ¯\_(ツ)_/¯

2021-11-25 22:17 UTC, saparjohnick commented on package.json
> +    "ramda": "^0.27.1",
спасибо! Видимо забыл --service-ports прописать при вызове консоли

2021-11-25 22:25 UTC, saparjohnick commented on app/javascript/utils/fetchHelper.js
> +      .then(camelize(params));
спасибо! это пофиксило camelize

2021-11-25 23:35 UTC, saparjohnick commented on app/javascript/components/TaskBoard/taskBoard.js
> +              isButtonHidden={buttonState}
убрал, спасибо

2021-11-25 23:37 UTC, saparjohnick commented on config/environments/development.rb
> +  config.web_console.whitelisted_ips = '172.19.0.1'
локально фронт не заводился, это решение из SO ) убрал

2021-11-25 23:38 UTC, saparjohnick commented on app/controllers/api/v1/tasks_controller.rb
> +      order(RANSACK_DEFAULT_SORT)
пофиксил следующие комменты -- пофиксился ордер на фронте, спасибо

2021-11-29 19:22 UTC, greybutton approved these changes
поправь пару моментов и можешь мержить

2021-11-29 19:22 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = search.
сделай, а здесь верни как было
```
  def ransack_params
    params.to_unsafe_h.fetch(:q, {}).with_defaults({ s: RANSACK_DEFAULT_SORT })
  end
```

2021-11-29 19:22 UTC, greybutton commented on app/javascript/utils/fetchHelper.js
> +  delete(url, json) {
json лишний

2021-11-30 18:17 UTC, saparjohnick commented
@greybutton спасибо! исправил

2021-11-30 18:17 UTC, merged