Feature/assignee
saparjohnick/task_manager pull request #16
Opened 2021-11-24 15:30 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/82/practices/1234
(add author/assignee on FE)

2021-11-25 16:59 UTC, greybutton requested changes
презентер везде нужно использовать, TaskBoard

2021-11-25 16:59 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +import UserPresenter from 'presenters/UserPresenter';
не используется

2021-11-25 16:59 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +  user: UserPresenter.shape(),
в пропсах нет этого

2021-11-25 16:59 UTC, greybutton commented on app/javascript/components/Form/Form.js
> +      />
автора нельзя выбирать/редактировать

2021-11-25 16:59 UTC, greybutton commented on app/javascript/components/Form/Form.js
> +  user: UserPresenter.shape(),
юзера нет в пропсах, ошибки есть, почему удалил?

2021-11-25 16:59 UTC, greybutton commented on app/javascript/components/Task/Task.js
> +  // task: PropTypes.shape().isRequired,
комментарий удалить

2021-11-25 16:59 UTC, greybutton commented on app/javascript/components/Task/Task.js
> +  task: TaskPresenter.shape(),
это осталось обязательным

2021-11-25 16:59 UTC, greybutton commented on app/javascript/presenters/UserPresenter.js
> +    last_name: PropTypes.string,
должен быть жс стиль, а не руби. firstName, lastName

2021-11-26 23:10 UTC, saparjohnick commented
спасибо @greybutton ! Вроде все поправил

2021-11-29 19:28 UTC, greybutton requested changes

2021-11-29 19:28 UTC, greybutton commented on app/javascript/components/TaskBoard/taskBoard.js
> +  task: TaskPresenter.shape().isRequired,
такого пропса нет в TaskBoard. Презентер нужно использовать вместо task.id, task.state и т.д. по всему проекту, тоже самое с юзер презентером

2021-11-30 19:30 UTC, saparjohnick commented on app/javascript/components/TaskBoard/taskBoard.js
> +  task: TaskPresenter.shape().isRequired,
Презентер для user вроде и так был, для task добавил. Теперь вроде везде только через презентеры

2021-11-30 19:43 UTC, saparjohnick commented
@greybutton я застрял на сл уроке с редаксом. 
После добавления кода из задачи, запускаю для теста -- выдает ошибку `loadColumn is not a function`  
в файле `hooks/store/useTasks.js` в Promise.all (сама loadColumn приходит undefined):
```
import { useSelector } from 'react-redux';
import { useTasksActions } from 'slices/TasksSlice';
import { states } from 'presenters/TaskPresenter';

const useTasks = () => {
  const board = useSelector(state => state.TasksSlice.board);
  const { loadColumn } = useTasksActions();
  const loadBoard = () => Promise.all(states.map(({ key }) => loadColumn(key)));

  return {
    board,
    loadBoard,
  };
};

export default useTasks;
```
функция импортируется из `slices/tasksSlice.js`:

```
export const useTasksActions = () => {
  const dispatch = useDispatch();

  const loadColumn = (state, page = 1, perPage = 10) => {
    TasksRepository.index({
      q: { stateEq: state },
      page,
      perPage,
    }).then(({ data }) => {
      dispatch(loadColumnSuccess({ ...data, columnId: state }));
    });
  };
  const loadBoard = () => STATES.map(({ key }) => loadColumn(key));

  return {
    loadBoard,
  };
};
```

2021-11-30 20:50 UTC, greybutton approved these changes

2021-11-30 20:52 UTC, greybutton commented
по редаксу создай реквест, там посмотрим, если совсем нет идей как заставить работать)

2021-12-01 08:52 UTC, merged