Feature/redux
saparjohnick/task_manager pull request #17
Opened 2021-12-01 16:54 UTC by saparjohnick

PR according to https://learn.dualboot.ru/courses/5/lessons/87/practices/1280

works everything except setTask callback in EditPopup.js -- so in edit card modal no info pre-filled about card 
![image](https://user-images.githubusercontent.com/8219832/144277894-71e29240-3705-40bd-be29-820827676e2d.png)

2021-12-01 18:20 UTC, saparjohnick commented
@sergeytabb pls help)

2021-12-02 17:52 UTC, greybutton requested changes
нет изменений в package.json

2021-12-02 17:52 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +              task={onLoadCard(cardId)}
сюда надо таску передавать, а не промис

2021-12-02 17:52 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +    setTask(cardId);
это не понятно зачем изменено

2021-12-02 17:52 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> -    });
тоже не понятно почему удалено

2021-12-02 17:52 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    loadBoard();
здесь надо подгружать данные, а не заново всю борду грузить

2021-12-02 17:52 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    loadBoard();
зачем всю борду заново грузить? можно одну колонку обновить. и у тебя после создания уже обновляется стор

2021-12-02 17:52 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +      loadBoard();
здесь одну колонку обновить можно

2021-12-02 17:52 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +import TaskPresenter from 'presenters/TaskPresenter';
перемешаны импорты. сначала либы, потом проектные файлы. из TaskPresenter можно в одну строку импорт сделать

2021-12-02 17:52 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +    const transition = task.transitions.find(
презентер забыл

2021-12-02 17:52 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +        loadColumnInitial(TaskPresenter.state(task));
у тебя нет объявления loadColumnInitial. откуда она?

2021-12-02 17:52 UTC, greybutton commented on app/javascript/App.js
> +      {/* <MUITheme> */}
тему надо добавить

2021-12-02 17:52 UTC, greybutton commented on app/javascript/components/TaskBoard/index.js
>  export default TaskBoard;
компонент больше не нужен, его можно удалить

2021-12-03 17:19 UTC, saparjohnick commented on app/javascript/slices/tasksSlice.js
> +    const transition = task.transitions.find(
а на что здесь презентер? на task.transitions.0.from ?

2021-12-03 17:20 UTC, saparjohnick commented on app/javascript/components/EditPopup/EditPopup.js
> +    setTask(cardId);
вернул
пытался пофиксить падение. падает в `then` в `onLoadCard(cardId).then(setTask);`
![image](https://user-images.githubusercontent.com/8219832/144645289-57731a3b-699d-4e84-9a45-d48fd0f4ca96.png)

2021-12-03 17:50 UTC, saparjohnick commented
@greybutton теперь не открыть модалку с редактированием из-за этого https://github.com/saparjohnick/task_manager/pull/17#discussion_r762115543

2021-12-06 19:49 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +    const transition = task.transitions.find(
TaskPresenter.transitions(task)

2021-12-06 19:52 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +    setTask(cardId);
значит не правильно пофиксил) надо разобраться почему у тебя не работает, `onLoadCard(cardId).then(setTask);` это верный код

2021-12-08 08:49 UTC, saparjohnick commented
вроде все пофиксил, все работает

2021-12-08 16:45 UTC, greybutton requested changes
молодец, что разобрался и теперь работает, но остались места над которыми еще нужно поработать

2021-12-08 16:45 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    loadColumn(destination);
это не лишнее? внутри dragEndCard есть загрузка колонок

2021-12-08 16:45 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +import _ from 'lodash';
зачем добавил? и не используется

2021-12-08 16:45 UTC, greybutton commented on app/javascript/slices/tasksSlice.js
> +    const transition = task.transitions.find(
здесь не добавил презентер

2021-12-08 16:45 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    return loadTask(id);
только здесь баг был, что промис не возвращался, хотя ожидался в onLoadCard

можно вернуть в слайсе 
```
  const loadTask = (id) => {
    return TasksRepository.show(id).then(({ data: { task } }) => task);
  };
```

в едитпопапе `onLoadCard(cardId).then(setTask);`

и тоже должно работать)

2021-12-08 16:45 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    loadColumn(INITIAL_STATE);
это не лишнее? внутри createTask есть загрузка колонки

2021-12-08 16:45 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    loadColumn(TaskPresenter.state(task));
это не лишнее? внутри updateTask есть загрузка колонки

2021-12-08 16:45 UTC, greybutton commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +      loadColumn(TaskPresenter.state(task));
это не лишнее? внутри destroyTask есть загрузка колонки

2021-12-09 09:08 UTC, saparjohnick commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    return loadTask(id);
спасибо) работает

2021-12-09 15:40 UTC, greybutton approved these changes

2021-12-09 20:02 UTC, merged