launch github actions
saparjohnick/task_manager pull request #18
Opened 2021-12-08 09:17 UTC by saparjohnick

https://learn.dualboot.ru/courses/5/lessons/77/practices/1158

github actions

2021-12-08 16:49 UTC, greybutton requested changes

2021-12-08 16:49 UTC, greybutton commented on README.md
> +[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fatrox%2Fsync-dotenv%2Fbadge&style=for-the-badge)](https://actions-badge.atrox.dev/atrox/sync-dotenv/go
вставлял ссылку на репозиторий и указывал develop ветку? как будто не совсем, то что нужно получилось

2021-12-09 09:17 UTC, saparjohnick commented on README.md
> +[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fatrox%2Fsync-dotenv%2Fbadge&style=for-the-badge)](https://actions-badge.atrox.dev/atrox/sync-dotenv/go
забыл) спасибо!

2021-12-09 15:41 UTC, greybutton approved these changes

2021-12-09 20:02 UTC, merged