try to add coveralls
saparjohnick/task_manager pull request #19
Opened 2021-12-08 10:11 UTC by saparjohnick

https://learn.dualboot.ru/courses/5/lessons/77/practices/1159

integrate coveralls

2021-12-08 16:52 UTC, greybutton requested changes

2021-12-08 16:52 UTC, greybutton commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/saparjohnick/task_manager/badge.svg?branch=feature/coveralls)](https://coveralls.io/github/saparjohnick/task_manager?branch=feature/coveralls)
поправь бейдж на ветку develop

2021-12-08 16:52 UTC, greybutton commented on .gitignore
> +coverage
добавил, но файлы все равно в реквесте

2021-12-08 16:52 UTC, greybutton commented on test/test_helper.rb
> +SimpleCov.start
нужно генерировать покрытие только в CI

2021-12-09 10:05 UTC, saparjohnick commented
вроде исправил

2021-12-09 15:44 UTC, greybutton requested changes

2021-12-09 15:44 UTC, greybutton commented on lcov.info
> +SF:./app/controllers/concerns/auth_helper.rb
забыл удалить этот файл из реквеста

2021-12-09 15:44 UTC, greybutton commented on test/test_helper.rb
> +  p 'IM HERE'
это можно удалить

2021-12-09 15:44 UTC, greybutton commented on test/test_helper.rb
> +
думаю этот код должен быть под 
```
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
require 'rails/test_help'
```

или есть причина почему выше?

2021-12-09 20:06 UTC, saparjohnick commented on test/test_helper.rb
> +
перемещу вниз
причины нет наверное, в туториале к либе было написано, что код должен быть в самом верху, но я не вижу причин не переместить

2021-12-09 20:14 UTC, saparjohnick commented on lcov.info
> +SF:./app/controllers/concerns/auth_helper.rb
)))
![image](https://user-images.githubusercontent.com/8219832/145468980-11458292-1184-43b5-8385-654241ad31ab.png)

2021-12-11 19:42 UTC, greybutton commented on lcov.info
> +SF:./app/controllers/concerns/auth_helper.rb
в таком случае файл надо генерировать во время покрытия

2021-12-11 19:42 UTC, greybutton commented on test/test_helper.rb
> +
хорошо

2021-12-11 20:52 UTC, saparjohnick commented
@greybutton help! Падает билд -- на одном шаге генерирую отчет (но он видимо сразу удаляется), на следующем пытаюсь его отправить и падает с ошибкой file not found
![image](https://user-images.githubusercontent.com/8219832/145691259-16eef472-ad8e-4878-b895-4a73a59c0856.png)

2021-12-11 22:06 UTC, saparjohnick commented
отчет генерируется в docker-compose и после выполнения команд удаляется =/

2021-12-11 22:55 UTC, saparjohnick commented
кажись решил

2021-12-12 16:58 UTC, greybutton approved these changes
засквошить бы все эти коммиты с попытками)

2021-12-14 12:55 UTC, merged