Feature/rollbar
saparjohnick/task_manager pull request #23
Opened 2021-12-19 18:37 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/77/practices/1162

![image](https://user-images.githubusercontent.com/8219832/146686799-a011939e-f655-4ccd-b5ed-3b8103d76208.png)

2021-12-20 13:47 UTC, NickelGit requested changes

2021-12-20 13:47 UTC, NickelGit commented on config/initializers/rollbar.rb
> +  config.access_token = '5c65c28d93cc4e338367ce22320992e3'
токены не хранят в коде. сгенерируй новый токен и добавь его через переменные окружения (environment variables)

2021-12-20 15:31 UTC, saparjohnick commented on config/initializers/rollbar.rb
> +  config.access_token = '5c65c28d93cc4e338367ce22320992e3'
спасибо @NickelGit ! пофиксил

2021-12-21 09:04 UTC, NickelGit approved these changes

2021-12-21 09:21 UTC, merged