install rubocop, factory-bot and execute rubocop
saparjohnick/task_manager pull request #3
Opened 2021-10-20 11:15 UTC by saparjohnick

done according to https://learn.dualboot.ru/courses/5/lessons/75/practices/1122

2021-10-21 10:53 UTC, greybutton requested changes
- не все гемы поставлены
- в остальных ПР дифф содержит изменения от предыдущей ветки, такого быть не должно

2021-10-21 12:44 UTC, saparjohnick commented
@greybutton спасибо! 
- добавил гемы в этот ПР
- остальным ПР изменил base

2021-10-21 18:18 UTC, greybutton approved these changes

2021-10-21 18:19 UTC, greybutton commented
почему коммиты от другого профиля?)

2021-10-22 15:05 UTC, merged

2021-10-22 15:07 UTC, saparjohnick commented
> почему коммиты от другого профиля?)

видимо локально за него залогинен )