Feature/generate models
saparjohnick/task_manager pull request #4
Opened 2021-10-20 17:57 UTC by saparjohnick

added models: Task, User -- Admin, Manager, Developer
added factories and tests
added bcrypt for executing tests

https://learn.dualboot.ru/courses/5/lessons/75/practices/1124

2021-10-21 18:21 UTC, greybutton requested changes
в целом ок, нужно будет отребейзить от девелопа после мерджа в девелоп feature/install-gems т.к. конфликт в гем файле. И поправить sequence

2021-10-21 18:21 UTC, greybutton commented on test/factories/sequence.rb
> +  sequence :int, aliases: [:author_id, :assignee_id] do |_n|
генерацию ид не нужно убирать в sequence

2021-10-22 15:11 UTC, saparjohnick commented on test/factories/sequence.rb
> +  sequence :int, aliases: [:author_id, :assignee_id] do |_n|
готово https://github.com/saparjohnick/task_manager/pull/4/commits/df6b26c814ae20b00ee1a2b024245eceace19f9d

2021-10-22 15:15 UTC, saparjohnick commented
готово )
https://github.com/saparjohnick/task_manager/pull/4/commits/bd6b59943ebd8833ba979563b80282e29c788de2

2021-10-22 19:15 UTC, greybutton approved these changes

2021-10-22 20:57 UTC, merged