Feature/material design
saparjohnick/task_manager pull request #7
Opened 2021-10-24 10:54 UTC by saparjohnick

PR according to https://learn.dualboot.ru/courses/5/lessons/76/practices/1143
created controllers 
added material design
configured simple_form

2021-10-25 18:51 UTC, greybutton requested changes
1 не хватает app/controllers/web/application_controller.rb

2021-10-25 18:51 UTC, greybutton commented on app/assets/stylesheets/application.css
> +//=require material-design-lite/material.min.js
это вроде надо после /**/ добавлять, а не внутри

2021-10-25 18:51 UTC, greybutton commented on config/routes.rb
> +  end
это зачем?

2021-10-25 18:51 UTC, greybutton commented on lib/templates/slim/scaffold/_form.html.slim
> +    = f.button :submit
это откуда? вроде не нужно

2021-10-26 17:42 UTC, saparjohnick commented on lib/templates/slim/scaffold/_form.html.slim
> +    = f.button :submit
генератор simple_form сам создал, убрал здесь https://github.com/saparjohnick/task_manager/pull/7/commits/6fefacd598676e4dbe09be53798fbefe18f00e7e

2021-10-26 17:52 UTC, saparjohnick commented on app/assets/stylesheets/application.css
> +//=require material-design-lite/material.min.js
Вне /**/ оно у меня красным подчеркивает ) 
переделал сдесь https://github.com/saparjohnick/task_manager/pull/7/commits/8c1deb6e26001d1d5913d230b84e3b7e292d6cda

2021-10-26 19:17 UTC, saparjohnick commented
@greybutton я исправил все, но у меня тесты не проходят из-за `//= require material-design-lite/material.min.js` и в браузере она выскакивает 

ошибка `ActionView::Template::Error: couldn't find file 'material-design-lite/material.min.js' with type 'text/css'`

2021-10-26 20:13 UTC, greybutton commented
css нужно импортировать, а не js `//= require material-design-lite/material.min.css`

2021-10-26 20:14 UTC, greybutton commented
> Merge branch 'feature/material-design' of github.com:saparjohnick/task_manager into feature/material-design

собственную ветку чтоли пулил? пул тоже с ребейсом делаем `git pull --rebase` чтобы таких коммитов не было

2021-10-26 20:23 UTC, saparjohnick commented
> css нужно импортировать, а не js `//= require material-design-lite/material.min.css`

спасибо!

2021-10-26 20:23 UTC, greybutton requested changes
теорию как будто пропускаешь местами

app/controllers/web/application_controller.rb
```
class Web::ApplicationController < ApplicationController
end
```

2021-10-26 20:23 UTC, greybutton commented on app/controllers/web/boards_controller.rb
> +class Web::BoardsController < ApplicationController
class Web::BoardsController < Web::ApplicationController

2021-10-26 20:23 UTC, greybutton commented on app/controllers/web/sessions_controller.rb
> +class Web::SessionsController < ApplicationController
class Web::SessionsController < Web::ApplicationController

2021-10-26 20:26 UTC, saparjohnick commented
> > Merge branch 'feature/material-design' of github.com:saparjohnick/task_manager into feature/material-design
> 
> собственную ветку чтоли пулил? пул тоже с ребейсом делаем `git pull --rebase` чтобы таких коммитов не было

это после мержа ветки `feature/state-machine` я решил попробовать `git rebase develop`, ничего не пулил) но получил какую-то ошибку при попытке запушить. В итоге после всех манипуляций получился такой коммит

2021-10-26 20:51 UTC, saparjohnick commented on app/controllers/web/sessions_controller.rb
> +class Web::SessionsController < ApplicationController
исправил https://github.com/saparjohnick/task_manager/pull/7/commits/77292b7d3653f22261afdcd8dcfcd902ff0406fb

2021-10-26 20:55 UTC, saparjohnick commented on app/controllers/web/boards_controller.rb
> +class Web::BoardsController < ApplicationController
исправил  [здесь](https://github.com/saparjohnick/task_manager/pull/7/commits/7e4dbe2a24f9bc3f0ac476bed1d039d03e536bf2)
\+ [мелкое](https://github.com/saparjohnick/task_manager/pull/7/commits/67eb0c16f02eb400ee0c754e1cb3e8b59357e9f4)

2021-10-27 10:03 UTC, greybutton commented
после ребейса форс пушить нужно)

2021-10-27 10:03 UTC, greybutton approved these changes

2021-10-27 16:05 UTC, merged